repo: https://github.com/devtoolsets/picker
httpRetry: 3
httpTimeout: 3
output: wiki
max_workers: 64
proxy:
  url: http://127.0.0.1:7890
  enable: false
feeds:
  Custom:
    enabled: true
    filename: config/CustomRSS.opml
  Research:
    enabled: true
    filename: config/ResearchRSS.opml
  Subscriptions-OnMyMac:
    enabled: true
    filename: config/Subscriptions-OnMyMac.opml
  CyberSecurity:
    enabled: true
    filename: config/CyberSecurityRSS.opml
    url: https://raw.githubusercontent.com/zer0yu/CyberSecurityRSS/master/CyberSecurityRSS.opml
  CyberSecurityRSS-tiny:
    enabled: true
    filename: config/CyberSecurityRSS-tiny.opml
    url: https://raw.githubusercontent.com/zer0yu/CyberSecurityRSS/master/tiny.opml
  Chinese-Independent-Blogs:
    enabled: true
    filename: config/chinese-independent-blogs.opml
    url: https://raw.githubusercontent.com/timqian/chinese-independent-blogs/master/feed.opml
  Chinese-Security:
    enabled: true
    filename: config/Chinese-Security-RSS.opml
    url: https://raw.githubusercontent.com/zhengjim/Chinese-Security-RSS/master/Chinese-Security-RSS.opml
  Security:
    enabled: true
    filename: config/SecureRss.opml
    url: https://github.com/Han0nly/SecurityRSS/blob/master/SecureRss.opml
  awesome-security-feed:
    enabled: true
    filename: config/awesome-security-feed.opml
    url: https://raw.githubusercontent.com/mrtouch93/awesome-security-feed/main/security_feeds.opml
  WeChat:
    enabled: true
    filename: config/wechatRSS.opml
    url: https://wechat2rss.xlab.app/opml/sec.opml
